# frozen_string_literal: true

module Bridge_api
  module Services
    module Types
      module ServiceGetV1ResponseTasksElementType
        extend Bridge_api::Internal::Types::Enum

        PATIENT_CONSENT = "PATIENT_CONSENT"
        PATIENT_INSURANCE = "PATIENT_INSURANCE"
        PATIENT_ADDRESS = "PATIENT_ADDRESS"
        SERVICE_LOCATION = "SERVICE_LOCATION"
        DATE_OF_SERVICE = "DATE_OF_SERVICE"
        DUPLICATE_SERVICE_TYPE = "DUPLICATE_SERVICE_TYPE"
        INVALID_INITIAL_SERVICE_TYPE = "INVALID_INITIAL_SERVICE_TYPE"
        REPLACE_NOTE = "REPLACE_NOTE"
        UPDATE_NOTE = "UPDATE_NOTE"
        TRIAGE = "TRIAGE"
        COVERAGE = "COVERAGE"
        PRIOR_AUTHORIZATION = "PRIOR_AUTHORIZATION"
        BILLING_TIME_LIMIT = "BILLING_TIME_LIMIT"
        PROVIDER_NOT_ENROLLED = "PROVIDER_NOT_ENROLLED"
        NOTE_SIGNING_PROVIDER_MISMATCH = "NOTE_SIGNING_PROVIDER_MISMATCH"
        THERAPY_DURATION = "THERAPY_DURATION"
        MINIMUM_DURATION = "MINIMUM_DURATION"
        MISSING_INITIATING_VISIT = "MISSING_INITIATING_VISIT"
        MISSING_ASSESSMENT = "MISSING_ASSESSMENT"
        MISSING_TIME_SPENT_MINUTES = "MISSING_TIME_SPENT_MINUTES"
        PATIENT_CONSENT_EXPIRED = "PATIENT_CONSENT_EXPIRED"
        INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
        INSUFFICIENT_MONITORING_DATA = "INSUFFICIENT_MONITORING_DATA"
        MISMATCHED_ICD_10 = "MISMATCHED_ICD10"
        BILLING_FREQUENCY_LIMIT = "BILLING_FREQUENCY_LIMIT"
        PATIENT_RECONSENT = "PATIENT_RECONSENT"
        PROVIDER_CHANGED = "PROVIDER_CHANGED"
      end
    end
  end
end
